#!/bin/sh
. $(dirname $(readlink -f $0))/servers.conf

wait_pid () {
    pid=$1
    forever=1
    i=0
    while [ $forever -gt 0 ]; do
        kill -0 $pid 1>/dev/null 2>&1
        if [ $? -eq 1 ]; then
            echo "OK"
            forever=0
        else
            kill -TERM "$pid"
            i=$((i + 1))
            if [ $i -gt 60 ]; then
                echo "ERROR"
                echo "Timed out while stopping (30s)"
                forever=0
            else
                sleep 0.5
            fi
        fi
    done
}

stop_gu () {
    echo -n "Stopping gunicorn... "
    if [ -f "$GUNICORN_PID_FILE" ]; then
        wait_pid $(cat "$GUNICORN_PID_FILE")
    else
        echo "NOT RUNNING"
    fi
}
start_gu () {
    echo -n "Starting gunicorn..."
    $ENVPYTHON $CEL_CHDIR/manage.py run_gunicorn -c $SERVERS_DIR/gunicorn
    echo "OK"
}
case "$1" in
  start)
    start_gu
    ;;
  stop)
    stop_gu
    ;;
  restart)
    stop_gu
    start_gu
    ;;
  *)
    echo "Usage: servers/gu {start|stop|restart}"
    exit 1
esac

exit 0
